@extends('layouts.app')

@section('title', 'All Reports - LimaSync')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1>All Reports</h1>
</div>

@if(session('success'))
    <div class="alert alert-success alert-dismissible fade show">
        {{ session('success') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
@endif

<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Report Title</th>
                        <th>Event</th>
                        <th>Type</th>
                        <th>Generated By</th>
                        <th>Date</th>
                        <th>Client Viewed</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($reports as $report)
                    <tr>
                        <td>{{ $report->report_title }}</td>
                        <td>
                            <a href="{{ route('events.show', $report->event) }}">
                                {{ $report->event->event_name ?? 'N/A' }}
                            </a>
                        </td>
                        <td>
                            <span class="badge bg-{{ $report->type_badge }}">
                                {{ $report->type_label }}
                            </span>
                        </td>
                        <td>{{ $report->generatedBy->full_name ?? 'N/A' }}</td>
                        <td>{{ $report->generated_at->format('d M Y H:i') }}</td>
                        <td>
                            @if($report->client_viewed)
                                <span class="badge bg-success">Yes</span>
                            @else
                                <span class="badge bg-secondary">No</span>
                            @endif
                        </td>
                        <td>
                            <a href="{{ route('reports.view', $report) }}" target="_blank" class="btn btn-sm btn-info">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="{{ route('reports.download', $report) }}" class="btn btn-sm btn-primary">
                                <i class="fas fa-download"></i>
                            </a>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" class="text-center">No reports generated yet.</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        {{ $reports->links() }}
    </div>
</div>
@endsection