@extends('layouts.app')

@section('title', 'Reports - ' . $event->event_name . ' - LimaSync')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h1>{{ $event->event_name }} - Reports</h1>
        <p class="mb-4">
            <i class="fas fa-calendar"></i> {{ $event->start_date->format('d M Y') }} &nbsp;|&nbsp;
            <i class="fas fa-map-marker-alt"></i> {{ $event->venue ?? 'N/A' }}
        </p>
    </div>
    <div>
        <a href="{{ route('client.dashboard') }}" class="btn btn-secondary">
            <i class="fas fa-arrow-left"></i> Back to Dashboard
        </a>
    </div>
</div>

@if(session('success'))
    <div class="alert alert-success alert-dismissible fade show">
        <i class="fas fa-check-circle"></i> {{ session('success') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger alert-dismissible fade show">
        <i class="fas fa-exclamation-circle"></i> {{ session('error') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
@endif

<!-- Event Summary Card -->
<div class="card mb-4">
    <div class="card-body">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h5 class="mb-0">Event Progress</h5>
                <small class="text-muted">{{ $event->progress_percentage }}% Complete</small>
                <div class="progress mt-2" style="height: 20px;">
                    <div class="progress-bar bg-{{ 
                        $event->progress_percentage == 100 ? 'success' : 
                        ($event->progress_percentage >= 50 ? 'warning' : 'danger') 
                    }}" 
                         role="progressbar" 
                         style="width: {{ $event->progress_percentage }}%">
                        {{ $event->progress_percentage }}%
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-end">
                <span class="badge bg-{{ 
                    $event->status == 'completed' ? 'success' : 
                    ($event->status == 'in_progress' ? 'warning' : 'secondary') 
                }}" style="font-size: 1rem; padding: 8px 16px;">
                    {{ ucfirst($event->status) }}
                </span>
            </div>
        </div>
    </div>
</div>

<!-- Reports Table -->
<div class="card">
    <div class="card-header">
        <h5 class="mb-0" style="color: white"><i class="fas fa-file-alt"></i> Available Reports</h5>
    </div>
    <div class="card-body">
        @if($reports->count() > 0)
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Report Title</th>
                            <th>Type</th>
                            <th>Generated By</th>
                            <th>Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($reports as $report)
                        <tr>
                            <td>{{ $report->report_title }}</td>
                            <td>
                                <span class="badge bg-{{ $report->type_badge }}">
                                    {{ $report->type_label }}
                                </span>
                            </td>
                            <td>{{ $report->generatedBy->full_name ?? 'N/A' }}</td>
                            <td>{{ $report->generated_at->format('d M Y H:i') }}</td>
                            <td>
                                <a href="{{ route('client.reports.view', $report) }}" 
                                   target="_blank" 
                                   class="btn btn-sm btn-info" 
                                   title="View">
                                    <i class="fas fa-eye"></i> View
                                </a>
                                <a href="{{ route('client.reports.download', $report) }}" 
                                   class="btn btn-sm btn-primary" 
                                   title="Download">
                                    <i class="fas fa-download"></i> Download
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @else
            <div class="text-center py-5">
                <i class="fas fa-file-alt fa-4x text-muted mb-3"></i>
                <p class="text-muted mb-0">No reports are available yet.</p>
                <small class="text-muted">Reports will appear here once Lima Deria generates them.</small>
            </div>
        @endif
    </div>
</div>
@endsection