@extends('layouts.app')

@section('title', 'Reports - ' . $event->event_name . ' - LimaSync')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h1>{{ $event->event_name }} - Reports</h1>
        <p class="mb-4">
            <i class="fas fa-users"></i> {{ $event->client->company_name ?? 'N/A' }} &nbsp;|&nbsp;
            <i class="fas fa-calendar"></i> {{ $event->start_date->format('d M Y') }}
        </p>
    </div>
    <div>
        <a href="{{ route('reports.create', $event) }}" class="btn btn-primary">
            <i class="fas fa-plus"></i> Generate Report
        </a>
        <a href="{{ route('events.show', $event) }}" class="btn btn-secondary">
            <i class="fas fa-arrow-left"></i> Back to Event
        </a>
    </div>
</div>

<!-- Event Readiness -->
<div class="card mb-4">
    <div class="card-body">
        <div class="row align-items-center">
            <div class="col-md-6">
                <h5 class="mb-0">Event Progress</h5>
                <small class="text-muted">{{ $event->progress_percentage }}% Complete</small>
            </div>
            <div class="col-md-6">
                <div class="progress" style="height: 20px;">
                    <div class="progress-bar" role="progressbar" 
                         style="width: {{ $event->progress_percentage }}%">
                        {{ $event->progress_percentage }}%
                    </div>
                </div>
            </div>
        </div>
        @if($event->isReadyForReport())
            <div class="alert alert-success mt-3 mb-0">
                <i class="fas fa-check-circle"></i> Event is ready for final report generation!
            </div>
        @else
            <div class="alert alert-warning mt-3 mb-0">
                <i class="fas fa-exclamation-triangle"></i> Event is not fully complete yet. Complete all checklists to generate a final report.
            </div>
        @endif
    </div>
</div>

<!-- Reports Table -->
<div class="card">
    <div class="card-header">
        <h5 class="mb-0">Generated Reports</h5>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Report Title</th>
                        <th>Type</th>
                        <th>Generated By</th>
                        <th>Date</th>
                        <th>Client Viewed</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($reports as $report)
                    <tr>
                        <td>{{ $report->report_title }}</td>
                        <td>
                            <span class="badge bg-{{ $report->type_badge }}">
                                {{ $report->type_label }}
                            </span>
                        </td>
                        <td>{{ $report->generatedBy->full_name ?? 'N/A' }}</td>
                        <td>{{ $report->generated_at->format('d M Y H:i') }}</td>
                        <td>
                            @if($report->client_viewed)
                                <span class="badge bg-success">Yes</span>
                            @else
                                <span class="badge bg-secondary">No</span>
                            @endif
                        </td>
                        <td>
                            <a href="{{ route('reports.view', $report) }}" target="_blank" class="btn btn-sm btn-info">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="{{ route('reports.download', $report) }}" class="btn btn-sm btn-primary">
                                <i class="fas fa-download"></i>
                            </a>
                            <form action="{{ route('reports.destroy', $report) }}" method="POST" class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Delete this report?')">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="6" class="text-center">
                            No reports generated yet. 
                            <a href="{{ route('reports.create', $event) }}">Generate one</a>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection